### ISSUE TITLE
why cannot I get the url in one cell ? 

### ISSUE THREAD

**Issue by 12rambau** [davidbrochart/ipyurl#2]
In the example the workflow is the following : 
```python
w = Url()
w
```
```python
w.url
```

I tested it on my end and it works as expected. 

Now if i try to run:
```python 
w = Url()
w.url
```

in 1 cell, I get `''`as a result. Why isn't it working in one cell (and by extension in a python script) ?

**Comment by davidbrochart** [comment]
Because you need to instantiate the widget. That is what this does:
```python
w
```
This cannot work in a Python script because it is a Jupyter notebook feature.
But there is another way:
```python
url = None
async def foo():
    global url
    w = Url()
    display(w)
    url = await w.get_url()
asyncio.ensure_future(foo())
```
`url` will be set after some time it your environment is async.

**Comment by 12rambau** [comment]
so using `display` is not instanciating anything correct ?

**Comment by davidbrochart** [comment]
It's displaying the widget `w`, then you await the URL.

**Comment by 12rambau** [comment]
ok, then If i want to get the url in a notebook let's say like this one:
```python
w = Url()
w
```
```pyhton
# do stuff with url 
w.url
```

How can I launch it in voila ?

**Comment by davidbrochart** [comment]
Voilà is another beast, it will launch all the cells one after the other, so the URL might not be retrieved from the front-end when you do `w.url`. Something like that could work:
```python
url = None
async def foo():
    global url
    w = Url()
    display(w)
    url = await w.get_url()
await asyncio.ensure_future(foo())
```

**Comment by 12rambau** [comment]
> Voilà is another beast

Unfortunately for me it's the beast I need to focus on ;-) 

> Something like that could work

arf ok so I tried your last piece of code and even in a jupyter notebook it awaits forever. It seems that the widget cannot be instanciated if I don't leave the cell

**Comment by davidbrochart** [comment]
Ah yes, you're right, it's deadlocking. See also:
- https://github.com/ipython/ipykernel/issues/646
- https://github.com/ipython/ipykernel/pull/589

One solution could be to use [akernel](https://github.com/davidbrochart/akernel).

**Comment by 12rambau** [comment]
thank you for the links, I'll explore the solutions and share what work for me before closing the issue

**Comment by artttt** [comment]
Take a look at https://github.com/Kirill888/jupyter-ui-poll
I believe this will solve this issue

****edited to add example using this package now i have my install issues sorted out.****

```python
from ipyurl import Url
from IPython.display import display
from jupyter_ui_poll import run_ui_poll_loop

def window_url():
    """returns the url for the window that jupyter is running in"""
    w = Url()
    display(w)
    func = lambda: None if w.url == "" else w.url
    url = run_ui_poll_loop(func)
    return url

```

out of interest the same can also be done with ipyleaflet providing the url

```python
import ipyleaflet
from IPython.display import display
from jupyter_ui_poll import run_ui_poll_loop


def window_url():
    """returns the url for the window that jupyter is running in"""

    m = ipyleaflet.Map(zoom=0)
    m.layout.display = "none"
    display(m)
    func = lambda: None if m.window_url == "" else m.window_url
    url = run_ui_poll_loop(func)
    m.close()
    return url

**Comment by 12rambau** [comment]
thanks @artttt for the suggestions. I think with this + @davidbrochart insight, I have everything I need to make it work from my side.
